server_version: 1.3.1
server_url: https://github.com/privacybydesign/irma_api_server/releases/download/v{{ server_version }}/irma_api_server.zip
conf_path: /etc/irma_api_server
base_install_path: /opt
install_path: /opt/irma_api_server
http_port: 8088
https_port: 8444

irma_configuration: "https://github.com/privacybydesign/irma-demo-schememanager"
irma_configuration_name: irma-demo
irma_configuration_subpath: true
irma_configuration_branch: master

jwt_issuer: "apiserver"
reject_unfloored_validity_timestamps: "false"

enable_issuing: "false"
enable_verification: "false"
enable_signing: "false"

allow_unsigned_issue_requests: "false"
allow_unsigned_verification_requests: "false"
allow_unsigned_signature_requests: "false"

authorized_idps:
authorized_sps:
authorized_sigclients:

client_names:
